export const followers = [
  // Followers (not following back) - 20 users
  {
    id: "1",
    fullname: "Sarah Johnson",
    username: "@sarahj",
    avatar: "https://avatar.iran.liara.run/public/34",
    isFollowing: false,
  },
  {
    id: "2",
    fullname: "Michael Chen",
    username: "@mchendev",
    avatar: "https://avatar.iran.liara.run/public/12",
    isFollowing: false,
  },
  {
    id: "3",
    fullname: "Emma Wilson",
    username: "@emmaw",
    avatar: "https://avatar.iran.liara.run/public/45",
    isFollowing: false,
  },
  {
    id: "4",
    fullname: "James Rodriguez",
    username: "@jrod",
    avatar: "https://avatar.iran.liara.run/public/23",
    isFollowing: false,
  },
  {
    id: "5",
    fullname: "Sophia Lee",
    username: "@sophialee",
    avatar: "https://avatar.iran.liara.run/public/56",
    isFollowing: false,
  },
  {
    id: "6",
    fullname: "Oliver Brown",
    username: "@oliverb",
    avatar: "https://avatar.iran.liara.run/public/67",
    isFollowing: false,
  },
  {
    id: "7",
    fullname: "Isabella Garcia",
    username: "@isabellag",
    avatar: "https://avatar.iran.liara.run/public/78",
    isFollowing: false,
  },
  {
    id: "8",
    fullname: "Lucas Martin",
    username: "@lucasm",
    avatar: "https://avatar.iran.liara.run/public/15",
    isFollowing: false,
  },
  {
    id: "9",
    fullname: "Ava Thompson",
    username: "@avat",
    avatar: "https://avatar.iran.liara.run/public/28",
    isFollowing: false,
  },
  {
    id: "10",
    fullname: "Noah Davis",
    username: "@noahd",
    avatar: "https://avatar.iran.liara.run/public/37",
    isFollowing: false,
  },
  {
    id: "11",
    fullname: "Mia White",
    username: "@miaw",
    avatar: "https://avatar.iran.liara.run/public/42",
    isFollowing: false,
  },
  {
    id: "12",
    fullname: "Ethan Clark",
    username: "@ethanc",
    avatar: "https://avatar.iran.liara.run/public/51",
    isFollowing: false,
  },
  {
    id: "13",
    fullname: "Amelia Baker",
    username: "@ameliab",
    avatar: "https://avatar.iran.liara.run/public/64",
    isFollowing: false,
  },
  {
    id: "14",
    fullname: "Alexander Hall",
    username: "@alexh",
    avatar: "https://avatar.iran.liara.run/public/73",
    isFollowing: false,
  },
  {
    id: "15",
    fullname: "Charlotte King",
    username: "@charlottek",
    avatar: "https://avatar.iran.liara.run/public/18",
    isFollowing: false,
  },
  {
    id: "16",
    fullname: "William Turner",
    username: "@willt",
    avatar: "https://avatar.iran.liara.run/public/25",
    isFollowing: false,
  },
  {
    id: "17",
    fullname: "Harper Scott",
    username: "@harpers",
    avatar: "https://avatar.iran.liara.run/public/31",
    isFollowing: false,
  },
  {
    id: "18",
    fullname: "Mason Green",
    username: "@masong",
    avatar: "https://avatar.iran.liara.run/public/47",
    isFollowing: false,
  },
  {
    id: "19",
    fullname: "Evelyn Adams",
    username: "@evelyna",
    avatar: "https://avatar.iran.liara.run/public/59",
    isFollowing: false,
  },
  {
    id: "20",
    fullname: "Daniel Mitchell",
    username: "@danielm",
    avatar: "https://avatar.iran.liara.run/public/68",
    isFollowing: false,
  },
];

export const followingUsers = [
  {
    id: "21",
    fullname: "Sofia Martinez",
    username: "@sofiam",
    avatar: "https://avatar.iran.liara.run/public/14",
    isFollowing: true,
  },
  {
    id: "22",
    fullname: "Henry Wilson",
    username: "@henryw",
    avatar: "https://avatar.iran.liara.run/public/27",
    isFollowing: true,
  },
  {
    id: "23",
    fullname: "Victoria Taylor",
    username: "@victoriat",
    avatar: "https://avatar.iran.liara.run/public/39",
    isFollowing: true,
  },
  {
    id: "24",
    fullname: "Sebastian Cooper",
    username: "@sebastianc",
    avatar: "https://avatar.iran.liara.run/public/41",
    isFollowing: true,
  },
  {
    id: "25",
    fullname: "Scarlett Murphy",
    username: "@scarlettm",
    avatar: "https://avatar.iran.liara.run/public/53",
    isFollowing: true,
  },
  {
    id: "26",
    fullname: "Jack Peterson",
    username: "@jackp",
    avatar: "https://avatar.iran.liara.run/public/62",
    isFollowing: true,
  },
  {
    id: "27",
    fullname: "Luna Rivera",
    username: "@lunar",
    avatar: "https://avatar.iran.liara.run/public/71",
    isFollowing: true,
  },
  {
    id: "28",
    fullname: "Gabriel Ross",
    username: "@gabrielr",
    avatar: "https://avatar.iran.liara.run/public/16",
    isFollowing: true,
  },
  {
    id: "29",
    fullname: "Aria Wood",
    username: "@ariaw",
    avatar: "https://avatar.iran.liara.run/public/29",
    isFollowing: true,
  },
  {
    id: "30",
    fullname: "Leo Campbell",
    username: "@leoc",
    avatar: "https://avatar.iran.liara.run/public/35",
    isFollowing: true,
  },
  {
    id: "31",
    fullname: "Stella Parker",
    username: "@stellap",
    avatar: "https://avatar.iran.liara.run/public/44",
    isFollowing: true,
  },
  {
    id: "32",
    fullname: "Theodore Evans",
    username: "@theodoree",
    avatar: "https://avatar.iran.liara.run/public/57",
    isFollowing: true,
  },
  {
    id: "33",
    fullname: "Hazel Phillips",
    username: "@hazelp",
    avatar: "https://avatar.iran.liara.run/public/61",
    isFollowing: true,
  },
  {
    id: "34",
    fullname: "Christopher Gray",
    username: "@chrisg",
    avatar: "https://avatar.iran.liara.run/public/75",
    isFollowing: true,
  },
  {
    id: "35",
    fullname: "Chloe Bennett",
    username: "@chloeb",
    avatar: "https://avatar.iran.liara.run/public/19",
    isFollowing: true,
  },
  {
    id: "36",
    fullname: "Austin Reed",
    username: "@austinr",
    avatar: "https://avatar.iran.liara.run/public/24",
    isFollowing: true,
  },
  {
    id: "37",
    fullname: "Zoey Morgan",
    username: "@zoeym",
    avatar: "https://avatar.iran.liara.run/public/33",
    isFollowing: true,
  },
  {
    id: "38",
    fullname: "David Foster",
    username: "@davidf",
    avatar: "https://avatar.iran.liara.run/public/48",
    isFollowing: true,
  },
  {
    id: "39",
    fullname: "Penelope Hayes",
    username: "@penelopeh",
    avatar: "https://avatar.iran.liara.run/public/55",
    isFollowing: true,
  },
  {
    id: "40",
    fullname: "Maxwell Warren",
    username: "@maxw",
    avatar: "https://avatar.iran.liara.run/public/69",
    isFollowing: true,
  },
];
