import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "@/app/globals.css";
import { TransitionProvider } from "@/app/providers";
import AppLayout from "@/app/components/layout";

const ubuntu = Ubuntu({
  subsets: [],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TransitionProvider>
      <html lang="en">
        <body className={ubuntu.className}>
          <AppLayout>{children}</AppLayout>
        </body>
      </html>
    </TransitionProvider>
  );
}
